name: 3W
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - colorama=0.4.5
  - contourpy=1.0.5
  - cycler=0.11.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.1.0
  - flit-core=3.7.1
  - fonttools=4.37.3
  - freetype=2.12.1
  - gettext=0.19.8.1
  - glib=2.74.0
  - glib-tools=2.74.0
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - icu=70.1
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - intel-openmp=2022.1.0
  - ipykernel=6.16.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.19.0
  - jupyter=1.0.0
  - jupyter_client=8.6.1
  - jupyter_console=6.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.14
  - libffi=3.4.2
  - libglib=2.74.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libogg=1.3.4
  - libpng=1.6.38
  - libsodium=1.0.18
  - libsqlite=3.39.3
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.2
  - libxslt=1.1.35
  - libzlib=1.2.12
  - llvmlite=0.39.1
  - lxml=4.9.1
  - markupsafe=2.1.1
  - matplotlib-base=3.6.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2022.1.0
  - munkres=1.1.4
  - natsort=8.2.0
  - nbclient=0.6.8
  - nbconvert=7.0.0
  - nbconvert-core=7.0.0
  - nbconvert-pandoc=7.0.0
  - nbformat=5.6.1
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - numba=0.56.4
  - numpy=1.23.3
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - packaging=21.3
  - pandas=1.5.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pcre2=10.37
  - pickleshare=0.7.5
  - pip=22.2.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - plotly=5.13.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.31
  - prompt_toolkit=3.0.31
  - psutil=5.9.2
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.2.1
  - pywin32=303
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - qtconsole=5.3.2
  - qtconsole-base=5.3.2
  - qtpy=2.2.0
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - seaborn=0.12.0
  - seaborn-base=0.12.0
  - setuptools=65.4.0
  - sip=6.6.2
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - stack_data=0.5.1
  - statsmodels=0.13.2
  - tbb=2021.6.0
  - tenacity=8.1.0
  - terminado=0.15.0
  - threadpoolctl=3.1.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.4.0
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - tslearn=0.5.3.2
  - typing_extensions=4.3.0
  - tzdata=2022d
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - chardet==5.2.0
      - h5py==3.11.0
      - about-time==3.1.1
      - alive-progress==2.4.1
      - charset-normalizer==3.0.1
      - grapheme==0.6.0
      - htmlmin==0.1.12
      - idna==3.4
      - imagehash==4.3.1
      - jupyter-core==5.7.2
      - multimethod==1.9.1
      - networkx==3.0
      - pandas-profiling==3.6.3
      - phik==0.12.3
      - pillow==9.3.0
      - pydantic==1.10.4
      - pywavelets==1.4.1
      - pyyaml==6.0
      - requests==2.28.2
      - tangled-up-in-unicode==0.2.0
      - tqdm==4.64.1
      - typeguard==2.13.3
      - urllib3==1.26.14
      - visions==0.7.5
